//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyber_Awareness_Chatbot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyber_Awareness_Chatbot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] about_time {
            get {
                object obj = ResourceManager.GetObject("about_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHI1ZSw1aDF0LDVoaXQsYTU1LGFuYWwsYW51cyxhcjVlLGFycnNlLGFyc2UsYXNzLGFzcy1mdWNrZXIsYXNzZXMsYXNzZnVja2VyLGFzc2Z1a2thLGFzc2hvbGUsYXNzaG9sZXMsYXNzd2hvbGUsYV9zX3MsYiF0Y2gsYjAwYnMsYjE3Y2gsYjF0Y2gsYmFsbGJhZyxiYWxscyxiYWxsc2FjayxiYXN0YXJkLGJlYXN0aWFsLGJlYXN0aWFsaXR5LGJlbGxlbmQsYmVzdGlhbCxiZXN0aWFsaXR5LGJpK2NoLGJpYXRjaCxiaXRjaCxiaXRjaGVyLGJpdGNoZXJzLGJpdGNoZXMsYml0Y2hpbixiaXRjaGluZyxibG9vZHksYmxvdyBqb2IsYmxvd2pvYixibG93am9icyxib2lvbGFzLGJvbGxvY2ssYm9sbG9rLGJvbmVyLGJvb2IsYm9vYnMsYm9vb2JzLGJvb29vYnMsYm9vb29vYnMsYm9vb29v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string curse_words {
            get {
                return ResourceManager.GetString("curse_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          _nnnn_                      
        ///        dGGGGMMb     ,&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;.
        ///       @p~qp~~qMb    | Linux Rules! |
        ///       M|@||@) M|   _;..............&apos;
        ///       @,----.JM| -&apos;
        ///      JS^\__/  qKL
        ///     dZP        qKRb
        ///    dZP          qKKb
        ///   fZP            SMMb
        ///   HZM            MMMM
        ///   FqM            MMMM
        /// __| &quot;.        |\dS&quot;qML
        /// |    `.       | `&apos; \Zq
        ///_)      \.___.,|     .&apos;
        ///\____   )MMMMMM|   .&apos;
        ///     `-&apos;       `--&apos; .
        /// </summary>
        internal static string hacker_logo {
            get {
                return ResourceManager.GetString("hacker_logo", resourceCulture);
            }
        }
    }
}
